### ISSUE TITLE
Add instructions for Helix

### ISSUE THREAD

**Issue by alanvardy** [elixir-tools/credo-language-server#29]
Hello @mhanberg I love what you are doing here!

I managed to get this working with [Helix](https://github.com/helix-editor/helix) on main, which now supports multiple LSPs, by git cloning to get the executable and using the following in the `languages.toml` configuration:

```toml
[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = false
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-servers = ["elixir-ls", "credo"]

[language-server.elixir-ls]
command = "elixir-ls"
config = { elixirLS.dialyzerEnabled = true }

[language-server.credo]
command = "/path/to/executable/credo-language-server"
args = ["--stdio=true", "--port=999"]

```

Would there be a good place to add this example?

**Comment by mhanberg** [comment]
Hi! 

I think a good place for it is in the list of supported editors in the readme.

you can put the code in a details/summary so i looks

<details><summary>like this</summary>
<p>

```toml
[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = false
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-servers = ["elixir-ls", "credo"]

[language-server.elixir-ls]
command = "elixir-ls"
config = { elixirLS.dialyzerEnabled = true }

[language-server.credo]
command = "/path/to/executable/credo-language-server"
args = ["--stdio=true", "--port=999"]
```

</p>
</details>
